name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install

      - name: Run Tests
        run: |
          cd frontend
          npm test
          cd ../backend
          npm test

      - name: Build
        run: |
          cd frontend
          npm run build
